### ISSUE TITLE
error on latest sdk 6.2.0

### ISSUE THREAD

**Issue by nnkn** [markw65/prettier-extension-monkeyc#11]
Hi , I love your extension, it help me saved about 5kb mem useage!
but when I use the latest sdk v6.2.0, I can't get it work
~~~js
Starting optimization step...
ERROR: Internal: TypeError: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at collectClassInfo (c:\Users\nnknLu\.vscode\extensions\markw65.prettier-extension-monkeyc-2.0.65\node_modules\@markw65\monkeyc-optimizer\build\chunk-QINU6R5E.cjs:17416:51)
    at analyze (c:\Users\nnknLu\.vscode\extensions\markw65.prettier-extension-monkeyc-2.0.65\node_modules\@markw65\monkeyc-optimizer\build\chunk-QINU6R5E.cjs:17586:3)
    at async optimizeMonkeyC (c:\Users\nnknLu\.vscode\extensions\markw65.prettier-extension-monkeyc-2.0.65\node_modules\@markw65\monkeyc-optimizer\build\chunk-QINU6R5E.cjs:17747:17)
    at async MessagePort.<anonymous> (c:\Users\nnknLu\.vscode\extensions\markw65.prettier-extension-monkeyc-2.0.65\node_modules\@markw65\monkeyc-optimizer\build\worker-thread.cjs:34:66)
~~~
May I just wait for your updates? ^_^

**Comment by markw65** [comment]
Fixed in v2.0.66
